### ISSUE TITLE
The server closes almost instantly

### ISSUE THREAD

**Issue by retiform** [mopemope/meghanada-emacs#100]
`[2018-05-14` 21:24:16,137][INFO ][Main          : 125] main                   - Meghanada-Server Version:1.0.2-cdcce44
[2018-05-14 21:24:16,161][ERROR][EmacsServer   : 361] startServer            - Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:103) ~[meghanada-1.0.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_171]
	at meghanada.session.Session.createSession(Session.java:103) ~[meghanada-1.0.2.jar:?]
	at meghanada.session.Session.createSession(Session.java:95) ~[meghanada-1.0.2.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:355) [meghanada-1.0.2.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-1.0.2.jar:?]
[2018-05-14 21:24:16,172][INFO ][Main          :  69] lambda$main$0          - shutdown server
[2018-05-14 21:24:16,174][INFO ][Config        : 186] showMe
2018-05-14` 21:24:16,137][INFO ][Main          : 125] main                   - Meghanada-Server Version:1.0.2-cdcce44
[2018-05-14 21:24:16,161][ERROR][EmacsServer   : 361] startServer            - Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:103) ~[meghanada-1.0.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_171]
	at meghanada.session.Session.createSession(Session.java:103) ~[meghanada-1.0.2.jar:?]
	at meghanada.session.Session.createSession(Session.java:95) ~[meghanada-1.0.2.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:355) [meghanada-1.0.2.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-1.0.2.jar:?]
[2018-05-14 21:24:16,172][INFO ][Main          :  69] lambda$main$0          - shutdown server
[2018-05-14 21:24:16,174][INFO ][Config        : 186] showMemory             - memory usage (used/total/max): 22.00MB / 123.00MB / 926.00MB

**Comment by mopemope** [comment]
see https://github.com/mopemope/meghanada-emacs/issues/93
