### ISSUE TITLE
Unable to access local maven repository

### ISSUE THREAD

**Issue by udalrich** [mopemope/meghanada-emacs#12]
Our project has a nested module structure:

    root/
      pom.xml
      components/
          pom.xml
          proj1/
            pom.xml
            src/main/java/my/proj/Foo.java
          proj2/
            pom.xml

root/pom.xml defines a local Nexus repository by

    <properties>
      <external.repository.url>http://x.y.z.w:port/nexus/content/groups/public/</external.repository.url>
    </properties>

    <repositories>
        <repository>
            <id>local</id>
            <name>Local Nexus</name>
            <url>${external.repository.url}</url>
        </repository>
    </repositories>

The Nexus repository is configured to go fall-back to the maven central repository if a file is not available locally.

When I start the server in Foo.java, I see a lot of messages like this:

[2016-09-20 10:36:12,609][ERROR][POMParser     : 495] transferFailed         - Could not find artifact maven-plugins:maven-cobertura-plugin:plugin:1.3 in central (http://central.maven.org/maven2/)

and attempts to download jars which are only in ~/.m2 from maven central.  After a while, it throws this exception and exits.  It looks like the parser might not be doing the property substitution on the URL property.

    Exception in thread "main" meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.me:some-project:jar:0.0.1-SNAPSHOT from/to local (${external.repository.url}): Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:144)
        at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:33)
        at meghanada.session.Session.loadProject(Session.java:152)
        at meghanada.session.Session.findProject(Session.java:101)
        at meghanada.session.Session.createSession(Session.java:76)
        at meghanada.session.Session.createSession(Session.java:71)
        at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:61)
        at meghanada.Main.main(Main.java:92)
    Caused by: meghanada.project.ProjectParseException: meghanada.project.ProjectParseException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.me:some-project:jar:0.0.1-SNAPSHOT from/to local (${external.repository.url}): Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:144)
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:78)
        ... 7 more
    Caused by: meghanada.project.ProjectParseException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.me:some-project:jar:0.0.1-SNAPSHOT from/to local (${external.repository.url}): Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:144)
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:78)
        ... 8 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.me:some-project:jar:0.0.1-SNAPSHOT from/to local (${external.repository.url}): Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
        at meghanada.project.maven.POMParser.resolveArtifact(POMParser.java:357)
        at meghanada.project.maven.POMParser.resolveArtifactFromCode(POMParser.java:348)
        at meghanada.project.maven.POMParser.parseDependencies(POMParser.java:161)
        at meghanada.project.maven.POMParser.parsePom(POMParser.java:135)
        ... 9 more
    Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.me:some-project:jar:0.0.1-SNAPSHOT from/to local (${external.repository.url}): Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 16 more
    Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access ${external.repository.url} with type Local Nexus using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        ... 17 more
    Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access ${external.repository.url} with type Local Nexus using the available layout factories: Maven2RepositoryLayoutFactory
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:111)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        ... 18 more
    Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Cannot access ${external.repository.url} with type Local Nexus using the available layout factories: Maven2RepositoryLayoutFactory
        at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:142)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:107)
        ... 20 more
    Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Unsupported repository layout Local Nexus
        at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory.newInstance(Maven2RepositoryLayoutFactory.java:64)
        at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:111)
        ... 21 more

**Comment by mopemope** [comment]
I have fixed it. Please check latest version (v0.2.0). and call `M-x meghanada-install-server.`
