### ISSUE TITLE
No completion for System.out.

### ISSUE THREAD

**Issue by stardiviner** [mopemope/meghanada-emacs#125]
I'm using latest maghanada version `1.0.9`.
When I type in `System.` it give out correct completions. But for `System.out.`. It give out no completion candidates.

**Comment by stardiviner** [comment]
After I re-installed meghanada server, and restart Emacs, I found the completion completely not working.

And here is the log from `*meghanada-server-log*`:

```
[2018-10-24 14:09:59,107][INFO ][Main      : 130] Meghanada-Server Version:1.0.9-da45e3e
[2018-10-24 14:10:00,411][INFO ][MavenProje:  76] running maven. build classpath ...
[2018-10-24 14:10:00,413][INFO ][MavenProje: 175] run mvn: mvn dependency:build-classpath -Dmdep.outputFile=/tmp/meghanada-maven-classpath4122540014895073925.log
[2018-10-24 14:10:08,763][INFO ][Session   : 210] loaded project:/home/stardiviner/Documents/learning/Java/maven-test elapsed:8.355 s
[2018-10-24 14:10:09,246][INFO ][EmacsServe: 381] Start server Listen localhost port:41807
[2018-10-24 14:10:09,480][INFO ][EmacsServe: 403] client connected
[2018-10-24 14:10:11,111][INFO ][Config    : 135] create class index ... read 1 jars. elapsed:1.854 s
[2018-10-24 14:10:11,133][INFO ][CacheEvent:  67] start analyze sources ...
[2018-10-24 14:10:13,165][INFO ][Project   : 310] project maven-test compile and analyze (java) 1 files. force:true problem:0 elapsed:2.008 s
[2018-10-24 14:10:13,380][INFO ][Project   : 374] project maven-test compile and analyze (test) 1 files. force:true problem:0 elapsed:213.0 ms
[2018-10-24 14:10:13,382][INFO ][Config    : 135] analyzed and compiled. elapsed:2.243 s
[2018-10-24 14:10:13,384][INFO ][CacheEvent:  93] class index size:5602 total elapsed:4.140 s
[2018-10-24 14:10:13,387][INFO ][Config    : 198] memory usage (used/total/max): 103.00MB / 193.00MB / 1717.00MB
[2018-10-24 14:10:13,387][INFO ][CacheEvent:  98] Ready
[2018-10-24 14:10:13,511][ERROR][SystemEven:  28] Catching
jetbrains.exodus.ExodusException: Can't acquire environment lock after 0 ms.

 Lock owner info: 
Private property of Exodus: 11380@dark

jetbrains.exodus.io.LockingManager.lock(LockingManager.java:108)
jetbrains.exodus.io.LockingManager.lock(LockingManager.java:56)
jetbrains.exodus.io.FileDataWriter.lock(FileDataWriter.java:82)
jetbrains.exodus.log.Log.tryLock(Log.java:933)
jetbrains.exodus.log.Log.<init>(Log.java:91)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89)
meghanada.index.IndexDatabase.open(IndexDatabase.java:82)
meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94)
meghanada.index.IndexDatabase.on(IndexDatabase.java:136)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

	at jetbrains.exodus.log.Log.tryLock(Log.java:935) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.log.Log.<init>(Log.java:91) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.open(IndexDatabase.java:82) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.on(IndexDatabase.java:136) ~[meghanada-1.0.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [meghanada-1.0.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[2018-10-24 14:10:13,531][ERROR][SystemEven:  28] Catching
jetbrains.exodus.ExodusException: Can't acquire environment lock after 0 ms.

 Lock owner info: 
Private property of Exodus: 11380@dark

jetbrains.exodus.io.LockingManager.lock(LockingManager.java:108)
jetbrains.exodus.io.LockingManager.lock(LockingManager.java:56)
jetbrains.exodus.io.FileDataWriter.lock(FileDataWriter.java:82)
jetbrains.exodus.log.Log.tryLock(Log.java:933)
jetbrains.exodus.log.Log.<init>(Log.java:91)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89)
meghanada.index.IndexDatabase.open(IndexDatabase.java:82)
meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94)
meghanada.index.IndexDatabase.on(IndexDatabase.java:136)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

	at jetbrains.exodus.log.Log.tryLock(Log.java:935) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.log.Log.<init>(Log.java:91) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.open(IndexDatabase.java:82) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.on(IndexDatabase.java:136) ~[meghanada-1.0.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [meghanada-1.0.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[2018-10-24 14:10:13,575][ERROR][SystemEven:  28] Catching
jetbrains.exodus.ExodusException: Can't acquire environment lock after 0 ms.

 Lock owner info: 
Private property of Exodus: 11380@dark

jetbrains.exodus.io.LockingManager.lock(LockingManager.java:108)
jetbrains.exodus.io.LockingManager.lock(LockingManager.java:56)
jetbrains.exodus.io.FileDataWriter.lock(FileDataWriter.java:82)
jetbrains.exodus.log.Log.tryLock(Log.java:933)
jetbrains.exodus.log.Log.<init>(Log.java:91)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89)
meghanada.index.IndexDatabase.open(IndexDatabase.java:82)
meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94)
meghanada.index.IndexDatabase.on(IndexDatabase.java:136)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

	at jetbrains.exodus.log.Log.tryLock(Log.java:935) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.log.Log.<init>(Log.java:91) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94) ~[meghanada-1.0.9.jar:?]
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:89) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.open(IndexDatabase.java:82) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:94) ~[meghanada-1.0.9.jar:?]
	at meghanada.index.IndexDatabase.on(IndexDatabase.java:136) ~[meghanada-1.0.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.9.jar:?]
	at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [meghanada-1.0.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[2018-10-24 14:10:13,629][ERROR][SystemEven:  28] Catching
jetbrains.exodus.ExodusException: Can't acquire environment lock after 0 ms.

```
