### ISSUE TITLE
Meghanada server crashes while starting, "Please check *meghanada-server-log* buffer"

### ISSUE THREAD

**Issue by dennismayr** [mopemope/meghanada-emacs#126]
OS: Ubuntu 16.04
Emacs: `26.1` + Spacemacs stable `0.200.13`
Problem: Meghanada server crashes while starting,

`"Meghanada server starting..."`
`"Please check *meghanada-server-log* buffer"`.

*meghanada-server-log*

```java
2018-11-02 21:15:23,379][INFO ][Main      : 130] Meghanada-Server Version:1.0.9-da45e3e
[2018-11-02 21:15:23,401][ERROR][EmacsServe: 385] Catching
java.lang.IllegalArgumentException: Project not found. it searched from /home/dmayr, but it was not found project
	at meghanada.session.Session.lambda$createSession$0(Session.java:110) ~[meghanada-1.0.9.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_181]
	at meghanada.session.Session.createSession(Session.java:106) ~[meghanada-1.0.9.jar:?]
	at meghanada.session.Session.createSession(Session.java:98) ~[meghanada-1.0.9.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:379) [meghanada-1.0.9.jar:?]
	at meghanada.Main.main(Main.java:132) [meghanada-1.0.9.jar:?]
[2018-11-02 21:15:23,413][INFO ][Main      :  69] shutdown server
[2018-11-02 21:15:23,416][INFO ][Config    : 198] memory usage (used/total/max): 25,00MB / 123,00MB / 848,00MB
```

This happens with any file I open.
Where do I start debugging?

**Comment by mopemope** [comment]
@dennismayr see #93
