### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by alexeiz** [mopemope/meghanada-emacs#129]
I get this exception a lot in the `*meghanada-server-log*` buffer.  Any idea what could cause it?

```
[2018-11-30 13:27:03,184][ERROR][SystemEven:  28] Catching
java.io.UncheckedIOException: java.io.FileNotFoundException: _51.cfs
    at meghanada.index.DocumentSearcher.lambda$executeInTransaction$2(DocumentSearcher.java:164) ~[meghanada-1.0.10.jar:?]
    at jetbrains.exodus.env.EnvironmentImpl.executeInTransaction(EnvironmentImpl.java:1005) ~[meghanada-1.0.10.jar:?]
    at jetbrains.exodus.env.EnvironmentImpl.executeInTransaction(EnvironmentImpl.java:257) ~[meghanada-1.0.10.jar:?]
    at jetbrains.exodus.env.ContextualEnvironmentImpl.executeInTransaction(ContextualEnvironmentImpl.java:131) ~[meghanada-1.0.10.jar:?]
    at meghanada.index.DocumentSearcher.executeInTransaction(DocumentSearcher.java:155) ~[meghanada-1.0.10.jar:?]
    at meghanada.index.IndexDatabase.indexObject(IndexDatabase.java:95) ~[meghanada-1.0.10.jar:?]
    at meghanada.index.IndexDatabase.on(IndexDatabase.java:136) ~[meghanada-1.0.10.jar:?]
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
    at meghanada.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[meghanada-1.0.10.jar:?]
    at meghanada.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[meghanada-1.0.10.jar:?]
    at meghanada.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [meghanada-1.0.10.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.io.FileNotFoundException: _51.cfs
    at jetbrains.exodus.lucene.ExodusDirectory.openInput(ExodusDirectory.java:115) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.store.Directory.openInput(Directory.java:145) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.CompoundFileReader.<init>(CompoundFileReader.java:65) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:75) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:116) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter$ReaderPool.get(IndexWriter.java:696) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter$ReaderPool.get(IndexWriter.java:671) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.BufferedDeletesStream.applyDeletes(BufferedDeletesStream.java:244) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter.doFlush(IndexWriter.java:3615) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3552) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter.closeInternal(IndexWriter.java:1852) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1812) ~[meghanada-1.0.10.jar:?]
    at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1776) ~[meghanada-1.0.10.jar:?]
    at meghanada.index.DocumentSearcher.closeIndexWriter(DocumentSearcher.java:95) ~[meghanada-1.0.10.jar:?]
    at meghanada.index.DocumentSearcher.lambda$executeInTransaction$2(DocumentSearcher.java:161) ~[meghanada-1.0.10.jar:?]
    ... 15 more
```

**Comment by mattroid** [comment]
I'm also getting this exact error and it cause a "maghanda ready" to continously prompt in the mini buffer at the bottom of the screen.

**Comment by mopemope** [comment]
This issue is also related to the xodus issue.
Will it happen with the latest version?

**Comment by atamariya** [comment]
I don't see this issue with the latest version.
