### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by pandey-abhinav** [mopemope/meghanada-emacs#140]
Meghanada version : 1.0.13
Emacs version : 26.1
Operating System : Mac OS X 10.14

emacs init file settings for meghanada:
```
(use-package meghanada
  :ensure t
  :init
  (add-hook 'java-mode-hook 'meghanada-mode)
  :config
  (setq meghanada-java-path "/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java"))
```

meghanada server log :
```
meghanada.com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at meghanada.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache.get(LocalCache.java:3952) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) ~[meghanada-1.0.13.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:94) ~[meghanada-1.0.13.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:399) ~[meghanada-1.0.13.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:267) ~[meghanada-1.0.13.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:844) ~[meghanada-1.0.13.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:361) ~[meghanada-1.0.13.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$21(EmacsServer.java:265) ~[meghanada-1.0.13.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.0.13.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.0.13.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.0.13.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:363) ~[meghanada-1.0.13.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$36(EmacsServer.java:444) ~[meghanada-1.0.13.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.comp.Check.checkClassOverrideEqualsAndHash(Check.java:2027) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.comp.Check.checkClassOverrideEqualsAndHashIfNeeded(Check.java:2017) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4275) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1221) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:364) ~[meghanada-1.0.13.jar:?]
	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344) ~[meghanada-1.0.13.jar:?]
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:147) ~[meghanada-1.0.13.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:103) ~[meghanada-1.0.13.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:81) ~[meghanada-1.0.13.jar:?]
	at meghanada.project.Project.parseFile(Project.java:425) ~[meghanada-1.0.13.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:75) ~[meghanada-1.0.13.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:20) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) ~[meghanada-1.0.13.jar:?]
	at meghanada.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[meghanada-1.0.13.jar:?]
	... 19 more
```

**Comment by mopemope** [comment]
@pandey-abhinav The java compiler sometimes throws an NPE when compiling source files that can not be compiled correctly.
There is no workaround for this...
