### ISSUE TITLE
Meghanada Failing on NullPointerException

### ISSUE THREAD

**Issue by WammKD** [mopemope/meghanada-emacs#152]
I haven't used Meghanada for a bit but I haven't changed much of anything other than upgrading whenever the package manager had a new Meghanada update.

I've been able to build all of my projects manually so it's not an issue of them being unable to build but Meghanada keeps throwing up this error for every project:

```
[INFO ][Main      :  54] use java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
[INFO ][Main      :  55] use java runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
[INFO ][Main      :  59] use java vm: Java HotSpot(TM) 64-Bit Server VM 25.131-b11
[INFO ][ClassPathU:  26] add tools.jar path:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar
[INFO ][MavenProje:  83] running maven. build classpath ...
[INFO ][MavenProje: 182] run mvn: mvn dependency:build-classpath -Dmdep.outputFile=/private/var/folders/2b/5plh56092zxgdtjgjm2h_nww0000gq/T/meghanada-maven-classpath7693734318646962089.log
[ERROR][EmacsServe: 374] Catching
java.lang.NullPointerException: null
	at org.apache.maven.model.plugin.DefaultReportingConverter.convert(DefaultReportingConverter.java:243) ~[meghanada-1.2.0.jar:?]
	at org.apache.maven.model.plugin.DefaultReportingConverter.convert(DefaultReportingConverter.java:213) ~[meghanada-1.2.0.jar:?]
	at org.apache.maven.model.plugin.DefaultReportingConverter.convertReporting(DefaultReportingConverter.java:140) ~[meghanada-1.2.0.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:479) ~[meghanada-1.2.0.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:432) ~[meghanada-1.2.0.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:422) ~[meghanada-1.2.0.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:90) ~[meghanada-1.2.0.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:121) ~[meghanada-1.2.0.jar:?]
	at meghanada.session.Session.loadProject(Session.java:222) ~[meghanada-1.2.0.jar:?]
	at meghanada.session.Session.findProject(Session.java:142) ~[meghanada-1.2.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:108) ~[meghanada-1.2.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:102) ~[meghanada-1.2.0.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:359) [meghanada-1.2.0.jar:?]
	at meghanada.Main.main(Main.java:156) [meghanada-1.2.0.jar:?]
```

That's from the `*meghanada-server-log*` buffer; I wasn't able to find any logs under my `/tmp` directory.

I've been able to use Meghanada with these projects, in the past, so I know I've been able to have success, previously.

I'm running Emacs 26.2 on MacOS Mojave with Meghanada 1.2.0.

**Comment by halcyon** [comment]
Is it possible to share a project via github that it fails with so this can be reproduced? A minimal project would be ideal.

**Comment by atamariya** [comment]
This fails if you have reportSet element included:

```xml

<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>2.9</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>index</report>
							<report>dependencies</report>
							<report>dependency-convergence</report>
							<report>dependency-management</report>
							<report>plugins</report>
						</reports>
					</reportSet>
		        </reportSets>
			</plugin>
```

**Comment by WammKD** [comment]
Things seem to've fixed themselves. Meghanada tends to not do well when I open multiple projects in Emacs at once so perhaps that's part of what was causing the issue. Sans anything similar cropping up – again –, I'm going to close this.
