### ISSUE TITLE
Server fails to run - Exception in thread "main" java.lang.IllegalArgumentException: Project Not Found

### ISSUE THREAD

**Issue by alexmurray** [mopemope/meghanada-emacs#16]
meghanada-server as installed via emacs from meghanada-emacs fails to run - and shows the following error when launched manually:

    java -jar ~/.emacs.d/meghanada/meghanada.jar 
    [2016-10-06 11:30:05,369][INFO ][Main          :  90] main                   - Meghanada-Server Version:0.2.2-97eff10
    Exception in thread "main" java.lang.IllegalArgumentException: Project Not Found
    	at meghanada.session.Session.createSession(Session.java:78)
    	at meghanada.session.Session.createSession(Session.java:71)
    	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:61)
    	at meghanada.Main.main(Main.java:92)

**Comment by mopemope** [comment]
Meghanada require maven or gradle project. Please try your maven or gradle project directory.

**Comment by alexmurray** [comment]
Ah thanks - perhaps meghanada-emacs could capture this exception and signal to the user why it failed - ie. you could look for the 'Project Not Found' string in the server output and then (message) to the user that it looks like it is not a maven / gradle project?
