### ISSUE TITLE
java.nio.file.NoSuchFileException: /home/user/.gradle/caches/modules-2/files-2.1

### ISSUE THREAD

**Issue by io12** [mopemope/meghanada-emacs#178]
When I try to run the server, I get this output in `*meghanada-server-log*`:

```
[INFO ][Main      :  54] use java home: /usr/lib/jvm/java-8-openjdk/jre
[INFO ][Main      :  55] use java runtime: OpenJDK Runtime Environment 1.8.0_292-b10
[INFO ][Main      :  59] use java vm: OpenJDK 64-Bit Server VM 25.292-b10
[INFO ][ClassPathU:  26] add tools.jar path:/usr/lib/jvm/java-8-openjdk/lib/tools.jar
[INFO ][GradleProj: 171] loading gradle project:/home/user/.gradle
[ERROR][EmacsServe: 376] Catching
meghanada.project.ProjectParseException: java.nio.file.NoSuchFileException: /home/user/.gradle/caches/modules-2/files-2.1
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:229) ~[meghanada-1.3.1.jar:?]
	at meghanada.session.Session.loadProject(Session.java:226) ~[meghanada-1.3.1.jar:?]
	at meghanada.session.Session.findProject(Session.java:139) ~[meghanada-1.3.1.jar:?]
	at meghanada.session.Session.createSession(Session.java:111) ~[meghanada-1.3.1.jar:?]
	at meghanada.session.Session.createSession(Session.java:105) ~[meghanada-1.3.1.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:361) [meghanada-1.3.1.jar:?]
	at meghanada.Main.main(Main.java:153) [meghanada-1.3.1.jar:?]
Caused by: java.nio.file.NoSuchFileException: /home/user/.gradle/caches/modules-2/files-2.1
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_292]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_292]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_292]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:1.8.0_292]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:1.8.0_292]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:1.8.0_292]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[?:1.8.0_292]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[?:1.8.0_292]
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72) ~[?:1.8.0_292]
	at java.nio.file.Files.walk(Files.java:3574) ~[?:1.8.0_292]
	at java.nio.file.Files.walk(Files.java:3625) ~[?:1.8.0_292]
	at meghanada.project.gradle.GradleProject.analyzeFromDependencyTree(GradleProject.java:712) ~[meghanada-1.3.1.jar:?]
	at meghanada.project.gradle.GradleProject.analyzeDependencies(GradleProject.java:512) ~[meghanada-1.3.1.jar:?]
	at meghanada.project.gradle.GradleProject.parseIdeaModule(GradleProject.java:311) ~[meghanada-1.3.1.jar:?]
	at meghanada.project.gradle.GradleProject.parseIdeaModule(GradleProject.java:272) ~[meghanada-1.3.1.jar:?]
	at meghanada.project.gradle.GradleProject.lambda$parseProject$2(GradleProject.java:205) ~[meghanada-1.3.1.jar:?]
	at meghanada.utils.FunctionUtils.lambda$wrapIOConsumer$2(FunctionUtils.java:34) ~[meghanada-1.3.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:202) ~[meghanada-1.3.1.jar:?]
	... 6 more
```

**Comment by io12** [comment]
The issue seems to go away if I create an empty `build.gradle` in the project root.
