### ISSUE TITLE
server start failed, process stoped

### ISSUE THREAD

**Issue by stardiviner** [mopemope/meghanada-emacs#2]
```
  Meghanada-Server Starting ...
  Meghanada-Server Started
  meghanada-server process stopped
```

The upper messages in in emacs buffer `*Messages*` after I execute command `[M-x meghanada-server-start]`.

Emacs version: 25.1.50

**Comment by mopemope** [comment]
Meghanada-Server process start automatically.Please try latest master and README.md

**Comment by stardiviner** [comment]
I toggled the `-v` option from `meghanada-debug`.
And run command of start server jar directly in project.
Here is the output:

```
[2016-09-13 11:15:52,362][DEBUG][Main          :  59] main                   - set verbose flag(DEBUG)
[2016-09-13 11:15:52,370][DEBUG][Main          :  90] main                   - set port:55555, projectRoot:./, output:sexp
[2016-09-13 11:15:52,371][INFO ][Main          :  93] main                   - Meghanada-Server Version:0.1.0-30119eb
[2016-09-13 11:15:52,384][DEBUG][Session       :  86] findProject            - finding project from '/home/stardiviner/Projects/Eclipse/test' ...
[2016-09-13 11:15:52,385][DEBUG][Session       :  86] findProject            - finding project from '/home/stardiviner/Projects/Eclipse' ...
[2016-09-13 11:15:52,385][DEBUG][Session       :  86] findProject            - finding project from '/home/stardiviner/Projects' ...
[2016-09-13 11:15:52,386][DEBUG][Session       :  86] findProject            - finding project from '/home/stardiviner' ...
[2016-09-13 11:15:52,386][DEBUG][Session       :  86] findProject            - finding project from '/home' ...
[2016-09-13 11:15:52,387][DEBUG][Session       :  86] findProject            - finding project from '/' ...
Exception in thread "main" java.lang.IllegalArgumentException: Project Not Found
        at meghanada.session.Session.createSession(Session.java:78)
        at meghanada.session.Session.createSession(Session.java:71)
        at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:61)
        at meghanada.Main.main(Main.java:95)
```

But my directory `/home/stardiviner/Projects/Eclipse/test/` is a Java project directory.

**Comment by stardiviner** [comment]
1. I found it does not complete some Java keywords like `public static` etc.
2. And it have a lot of improvements. I will create some PRs.
