### ISSUE TITLE
Error in Maven project: NPE in meghanada.project.maven.MavenProject.parseProject

### ISSUE THREAD

**Issue by syl20bnr** [mopemope/meghanada-emacs#28]
Trying to test Meghanada with a Maven project: https://github.com/yandex-qatools/teamcity-openstack-plugin

When starting the server I've got this error:

```
[2017-02-09 23:26:01,880][INFO ][Main          : 101] main                   - Meghanada-Server Version:0.5.0-cb5c212
[2017-02-09 23:26:05,503][ERROR][EmacsServer   :  69] startServer            - Catching
java.lang.NullPointerException: null
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:69) ~[meghanada-0.5.0.jar:?]
	at meghanada.session.Session.loadProject(Session.java:164) ~[meghanada-0.5.0.jar:?]
	at meghanada.session.Session.findProject(Session.java:95) ~[meghanada-0.5.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:70) ~[meghanada-0.5.0.jar:?]
	at meghanada.session.Session.createSession(Session.java:65) ~[meghanada-0.5.0.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:64) [meghanada-0.5.0.jar:?]
	at meghanada.Main.main(Main.java:103) [meghanada-0.5.0.jar:?]
```

What is strange is that I tried with a gradle project, it worked fine and then it made the maven project to work too using `meghanada-client-direct-connect` (gradle 3.3 was even donwloaded for the maven project).

**Comment by mopemope** [comment]
@syl20bnr Meghanada support maven project not fully. Please check latest version and resolve dependencies like a ` mvn install`.

**Comment by mopemope** [comment]
@syl20bnr Could you try the latest version ?

**Comment by syl20bnr** [comment]
Seems fixed, wonderful work on Meghanada 💜
