### ISSUE TITLE
NPE while code completion

### ISSUE THREAD

**Issue by amol-mandhane** [mopemope/meghanada-emacs#30]
Meghanada version: 0.6.1

Server log:
```
[2017-02-19 20:35:03,996][ERROR][JavaCompletion:  65] completionAt           - Catching
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.6.1.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:148) ~[meghanada-0.6.1.jar:?]
	at meghanada.completion.JavaCompletion.getSource(JavaCompletion.java:43) ~[meghanada-0.6.1.jar:?]
	at meghanada.completion.JavaCompletion.completionAt(JavaCompletion.java:53) ~[meghanada-0.6.1.jar:?]
	at meghanada.session.Session.completionAt(Session.java:340) ~[meghanada-0.6.1.jar:?]
	at meghanada.server.CommandHandler.autocomplete(CommandHandler.java:89) ~[meghanada-0.6.1.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$5(EmacsServer.java:170) ~[meghanada-0.6.1.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.6.1.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.6.1.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.6.1.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:272) ~[meghanada-0.6.1.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:126) ~[meghanada-0.6.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:54) ~[meghanada-0.6.1.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:49) ~[meghanada-0.6.1.jar:?]
	at meghanada.project.Project.parseFile(Project.java:401) ~[meghanada-0.6.1.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:109) ~[meghanada-0.6.1.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.6.1.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.6.1.jar:?]
	... 19 more
```

**Comment by mopemope** [comment]
@amol-mandhane Meghanada-mode require meghanada-server and JDK (not JRE).
https://github.com/mopemope/meghanada-emacs/blob/master/README.md
