### ISSUE TITLE
meghanada-local-variable IOException

### ISSUE THREAD

**Issue by douglarek** [mopemope/meghanada-emacs#32]
When tried`"I am good";` with `meghanada-local-variable`, I got this:

```
[2017-02-22 10:52:25,703][ERROR][GlobalCache   : 167] lambda$readCacheFromFi - Catching
com.esotericsoftware.kryo.KryoException: java.io.IOException: Read error or truncated source
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:166) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.io.Input.require(Input.java:196) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:823) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:684) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.GlobalCache.lambda$readCacheFromFile$3(GlobalCache.java:164) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.GlobalCache.readCacheFromFile(GlobalCache.java:162) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.JavaSourceLoader.loadFromCache(JavaSourceLoader.java:74) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:99) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:22) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[meghanada-0.6.2.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[meghanada-0.6.2.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:148) ~[meghanada-0.6.2.jar:?]
	at meghanada.session.Session.parseJavaSource(Session.java:424) ~[meghanada-0.6.2.jar:?]
	at meghanada.session.Session.searchMissingImport(Session.java:414) ~[meghanada-0.6.2.jar:?]
	at meghanada.server.CommandHandler.importAll(CommandHandler.java:149) ~[meghanada-0.6.2.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$14(EmacsServer.java:228) ~[meghanada-0.6.2.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.6.2.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.6.2.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.6.2.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:272) ~[meghanada-0.6.2.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$2(EmacsServer.java:126) ~[meghanada-0.6.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.IOException: Read error or truncated source
	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:102) ~[meghanada-0.6.2.jar:?]
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:164) ~[meghanada-0.6.2.jar:?]
	... 32 more
```

**Comment by mopemope** [comment]
@douglarek This is not a problem. Cache error will automatically recover.
