### ISSUE TITLE
Feature Request: Find all callers ( references ) 

### ISSUE THREAD

**Issue by naclander** [mopemope/meghanada-emacs#41]
A common use case is finding all callers for a specific function. This can be useful for refactoring as well. Is there a plan to support this?

**Comment by mopemope** [comment]
@naclander  I hava a plan refernces feature.

**Comment by mopemope** [comment]
@naclander Support for searching references. Could you please try latest version ?

**Comment by songpeng** [comment]
[2017-06-26 09:40:47,103][ERROR][EmacsServer   : 321] lambda$acceptConnectio - Catching
com.leacox.motif.MatchException: No match found for [re, file.java, 140, 44, record]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:122) ~[meghanada-0.8.0.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:228) ~[meghanada-0.8.0.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$22(EmacsServer.java:308) ~[meghanada-0.8.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by songpeng** [comment]
Hi, @mopemope 
I try the 0.8.0 version on Emacs 25.2.1, mac port.
It seems everything is OK, but for finding references, it will get error, and connection is off.
The log is above. Sorry that I have to hide my source code information.
After I reconnect to the meghanada server, it's OK except again for the reference.

**Comment by mopemope** [comment]
@songpeng Thank you for your report. but I could not reproduce this.
I will investigate again if there is time available.

**Comment by songpeng** [comment]
@mopemope  
The reference is available now after I update meghanada to 0.8.1.
Thanks.
Songpeng
