### ISSUE TITLE
Cannot start server.

### ISSUE THREAD

**Issue by amosbird** [mopemope/meghanada-emacs#42]
The error log is,
```
meghanada.project.ProjectParseException: java.lang.RuntimeException: org.gradle.tooling.GradleConnectionException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'.
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:104) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.loadProject(Session.java:169) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.findProject(Session.java:96) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:75) ~[meghanada-0.7.5.jar:?]
	at meghanada.session.Session.createSession(Session.java:70) ~[meghanada-0.7.5.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:65) [meghanada-0.7.5.jar:?]
	at meghanada.Main.main(Main.java:116) [meghanada-0.7.5.jar:?]
Caused by: java.lang.RuntimeException: org.gradle.tooling.GradleConnectionException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'.
	at meghanada.config.Config.debugTimeItF(Config.java:123) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:86) ~[meghanada-0.7.5.jar:?]
	... 6 more
Caused by: org.gradle.tooling.GradleConnectionException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[meghanada-0.7.5.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46) ~[meghanada-0.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50) ~[meghanada-0.7.5.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.getModel(DefaultProjectConnection.java:41) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.lambda$parseProject$0(GradleProject.java:87) ~[meghanada-0.7.5.jar:?]
	at meghanada.config.Config.debugTimeItF(Config.java:121) ~[meghanada-0.7.5.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:86) ~[meghanada-0.7.5.jar:?]
	... 6 more
```

**Comment by amosbird** [comment]
After adding `apply plugin: 'idea'` to build.gradle, it works fine now.
