### ISSUE TITLE
Server crashes immediately on start

### ISSUE THREAD

**Issue by clarkenciel** [mopemope/meghanada-emacs#48]
I have run `meghanada-install-server` and upon starting the mode or running `meghanada-server-start`, it exits almost immediately.

from the Messages buffer:
```
Meghanada-Server Starting ...
t
error in process sentinel: meghanada--server-process-sentinel: Error:meghanada-server process stopped
error in process sentinel: Error:meghanada-server process stopped
```

Platform:
Mac OS 10.12.4
Java 1.8
emacs 25.2.1

**Comment by mopemope** [comment]
@clarkenciel Thank you for your report.
Could you please check `*meghanada-server-log*` buffer or `/tmp/meghanada_server.log` ?

**Comment by clarkenciel** [comment]
the log file you mention doesn't seem to exist for me and the log buffer disappears as soon as the server crashes so I can't yank any of the logs from it. however, if i run the jar file directly i get the following dump:
```
[2017-06-05 09:25:18,385][INFO ][Main          : 118] main                   - Meghanada-Server Version:0.7.9-26b0896
[2017-06-05 09:25:18,572][INFO ][GradleProject : 120] parseProject           - loading gradle project:/Users/dannyclarke/dsp/atom/build.gradle
[2017-06-05 09:25:19,141][ERROR][EmacsServer   : 249] startServer            - Catching
meghanada.project.ProjectParseException: java.lang.RuntimeException: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:160) ~[meghanada-0.7.9.jar:?]
	at meghanada.session.Session.loadProject(Session.java:184) ~[meghanada-0.7.9.jar:?]
	at meghanada.session.Session.findProject(Session.java:109) ~[meghanada-0.7.9.jar:?]
	at meghanada.session.Session.createSession(Session.java:88) ~[meghanada-0.7.9.jar:?]
	at meghanada.session.Session.createSession(Session.java:83) ~[meghanada-0.7.9.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:244) [meghanada-0.7.9.jar:?]
	at meghanada.Main.main(Main.java:120) [meghanada-0.7.9.jar:?]
Caused by: java.lang.RuntimeException: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
	at meghanada.config.Config.debugTimeItF(Config.java:124) ~[meghanada-0.7.9.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:123) ~[meghanada-0.7.9.jar:?]
	... 6 more
Caused by: org.gradle.tooling.BuildException: Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51) ~[meghanada-0.7.9.jar:?]
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29) ~[meghanada-0.7.9.jar:?]
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41) ~[meghanada-0.7.9.jar:?]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46) ~[meghanada-0.7.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_131]
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46) ~[meghanada-0.7.9.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50) ~[meghanada-0.7.9.jar:?]
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.getModel(DefaultProjectConnection.java:41) ~[meghanada-0.7.9.jar:?]
	at meghanada.project.gradle.GradleProject.lambda$parseProject$0(GradleProject.java:124) ~[meghanada-0.7.9.jar:?]
	at meghanada.config.Config.debugTimeItF(Config.java:122) ~[meghanada-0.7.9.jar:?]
	at meghanada.project.gradle.GradleProject.parseProject(GradleProject.java:123) ~[meghanada-0.7.9.jar:?]
	... 6 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/dannyclarke/dsp/atom/build.gradle' line: 8
A problem occurred evaluating root project 'atom'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74) ~[?:?]
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47) ~[?:?]
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:101) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:87) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:102) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:48) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.util.Swapper.swap(Swapper.java:38) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) ~[?:?]
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246) ~[?:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) ~[meghanada-0.7.9.jar:?]
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'atom'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93) ~[?:?]
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25) ~[?:?]
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55) ~[?:?]
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:529) ~[?:?]
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90) ~[?:?]
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42) ~[?:?]
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125) ~[?:?]
	at org.gradle.internal.Factories$1.create(Factories.java:22) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:87) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:102) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:48) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.util.Swapper.swap(Swapper.java:38) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) ~[?:?]
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246) ~[?:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) ~[meghanada-0.7.9.jar:?]
Caused by: groovy.lang.MissingPropertyException: Could not find property 'artifactory_contextUrl' on org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@20e6c4f9.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43) ~[?:?]
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35) ~[?:?]
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97) ~[?:?]
	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated.getProperty(Unknown Source) ~[?:?]
	at build_8d3u5dy7f2krik0d9txqa2mz2$_run_closure1$_closure2$_closure5.doCall(/Users/dannyclarke/dsp/atom/build.gradle:8) ~[?:?]
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67) ~[?:?]
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:87) ~[?:?]
	at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.maven(DefaultRepositoryHandler.java:89) ~[?:?]
	at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.maven(DefaultRepositoryHandler.java:93) ~[?:?]
	at build_8d3u5dy7f2krik0d9txqa2mz2$_run_closure1$_closure2.doCall(/Users/dannyclarke/dsp/atom/build.gradle:7) ~[?:?]
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110) ~[?:?]
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:66) ~[?:?]
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:33) ~[?:?]
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91) ~[?:?]
	at org.gradle.api.internal.initialization.DefaultScriptHandler.repositories(DefaultScriptHandler.java:87) ~[?:?]
	at build_8d3u5dy7f2krik0d9txqa2mz2$_run_closure1.doCall(/Users/dannyclarke/dsp/atom/build.gradle:2) ~[?:?]
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130) ~[?:?]
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91) ~[?:?]
	at org.gradle.api.internal.project.AbstractProject.buildscript(AbstractProject.java:900) ~[?:?]
	at org.gradle.api.Project$buildscript.call(Unknown Source) ~[?:?]
	at org.gradle.api.internal.project.ProjectScript.buildscript(ProjectScript.groovy:47) ~[?:?]
	at org.gradle.api.Script$buildscript.callCurrent(Unknown Source) ~[?:?]
	at build_8d3u5dy7f2krik0d9txqa2mz2.run(/Users/dannyclarke/dsp/atom/build.gradle:1) ~[?:?]
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91) ~[?:?]
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38) ~[?:?]
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25) ~[?:?]
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34) ~[?:?]
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55) ~[?:?]
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:529) ~[?:?]
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90) ~[?:?]
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42) ~[?:?]
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125) ~[?:?]
	at org.gradle.internal.Factories$1.create(Factories.java:22) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) ~[?:?]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93) ~[?:?]
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:87) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:102) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:48) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58) ~[?:?]
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43) ~[?:?]
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81) ~[?:?]
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.util.Swapper.swap(Swapper.java:38) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41) ~[?:?]
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120) ~[?:?]
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) ~[?:?]
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246) ~[?:?]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) ~[meghanada-0.7.9.jar:?]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) ~[meghanada-0.7.9.jar:?]
[2017-06-05 09:25:19,163][INFO ][Main          :  65] lambda$main$0          - shutdown server

```

**Comment by clarkenciel** [comment]
I couldn't find either of those: it looks like the log buffer closes as soon as meghanada-server crashes and the log file didn't seem to exist. however, running the jar directly in my project directory revealed that the problem was in my gradle configuration, so i'm going to close.
