### ISSUE TITLE
meghanada error when start version 0.8.1

### ISSUE THREAD

**Issue by songpeng** [mopemope/meghanada-emacs#52]
[2017-06-28 13:54:02,919][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.1-54ea766
Exception in thread "main" java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at meghanada.server.emacs.EmacsServer.<init>(EmacsServer.java:56)
	at meghanada.Main.createServer(Main.java:153)
	at meghanada.Main.main(Main.java:126)

**Comment by songpeng** [comment]
Hi, 
I did not meet this situation before until recently I update meghanda to 0.8.1.
I use MacOS，Emacs version 25.2.1.
When I open one java file in a project first time, it always get this error after meghanada ready.

**Comment by songpeng** [comment]
This problem still exists after I retried `mvn clean install` or build the meghanada server directly from github repository.

**Comment by mopemope** [comment]
@songpeng It's because the Java process has not terminated properly. Could you please kill meghanada-server process.

**Comment by songpeng** [comment]
Hi,
thanks a lot for your remind. This problem is solved after I restart my computer. 
Before that, I tried to `M-x meghanada-server kill` or `M-x meghanada-server update` or even restart Emacs. The problem is still there.
Thanks a lot for your answer!
Songpeng
