### ISSUE TITLE
Error when starting Meghanada-Server

### ISSUE THREAD

**Issue by hnisonoff** [mopemope/meghanada-emacs#58]
I am using Emacs 25.1.1 with JDK 1.8 installed. I am using MacOS.
I downloaded from Melpa and have verified that the server is downloaded in the default location.

When the server is started, I get the following error:
```
Meghanada-Server Starting ...
error in process sentinel: meghanada--server-process-sentinel: Error:meghanada-server process stopped: finished
. Please check *meghanada-server-log* buffer
```

The log says:
```
[2017-08-06 00:32:01,447][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-08-06 00:32:01,465][ERROR][EmacsServer   : 311] startServer            - Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:100) ~[meghanada-0.8.3.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_101]
	at meghanada.session.Session.createSession(Session.java:100) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:92) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:306) [meghanada-0.8.3.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-0.8.3.jar:?]
[2017-08-06 00:32:01,474][INFO ][Main          :  69] lambda$main$0          - shutdown server
[2017-08-06 00:32:01,476][INFO ][Config        : 178] showMemory             - memory usage (used/total/max): 21.00MB / 123.00MB / 725.00MB
```

Can you help me debug this? Thanks!

**Comment by mopemope** [comment]
@hnisonoff  Meghanada require maven or gradle project. Please try your maven or gradle project directory.
