### ISSUE TITLE
Meghanada does not work under Tramp

### ISSUE THREAD

**Issue by naclander** [mopemope/meghanada-emacs#71]
It claims the project is now able to be found with the following stack trace:

```
[2017-10-03 11:23:48,276][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-10-03 11:23:48,299][ERROR][EmacsServer   : 311] startServer            - Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:100) ~[meghanada-0.8.3.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_144]
	at meghanada.session.Session.createSession(Session.java:100) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:92) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:306) [meghanada-0.8.3.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-0.8.3.jar:?]
```

**Comment by mopemope** [comment]
meghanada not supported tramp.

**Comment by naclander** [comment]
@mopemope can this be a feature request?
