### ISSUE TITLE
NullPointerError whenever the cursor on top of a function

### ISSUE THREAD

**Issue by MAliNaqvi** [mopemope/meghanada-emacs#75]
I have installed JDK 8

![meghanada-server_error](https://user-images.githubusercontent.com/13531332/32377276-766f794c-c07d-11e7-9154-856f4fdea3c3.png)

```
[2017-11-03 09:49:13,475][ERROR][CommandHandler:  47] writeError             - Catching
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[meghanada-0.8.3.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:94) ~[meghanada-0.8.3.jar:?]
	at meghanada.utils.FileUtils.getSource(FileUtils.java:379) ~[meghanada-0.8.3.jar:?]
	at meghanada.docs.declaration.DeclarationSearcher.searchDeclaration(DeclarationSearcher.java:265) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.showDeclaration(Session.java:699) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.CommandHandler.showDeclaration(CommandHandler.java:329) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$16(EmacsServer.java:208) ~[meghanada-0.8.3.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-0.8.3.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-0.8.3.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:290) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$29(EmacsServer.java:370) ~[meghanada-0.8.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
	at meghanada.analyze.JavaAnalyzer.runAnalyzeAndCompile(JavaAnalyzer.java:140) ~[meghanada-0.8.3.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:126) ~[meghanada-0.8.3.jar:?]
	at meghanada.analyze.JavaAnalyzer.analyzeAndCompile(JavaAnalyzer.java:104) ~[meghanada-0.8.3.jar:?]
	at meghanada.project.Project.parseFile(Project.java:413) ~[meghanada-0.8.3.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:75) ~[meghanada-0.8.3.jar:?]
	at meghanada.cache.JavaSourceLoader.load(JavaSourceLoader.java:20) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[meghanada-0.8.3.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[meghanada-0.8.3.jar:?]
	... 19 more

```

**Comment by mopemope** [comment]
@MAliNaqvi see 
https://github.com/mopemope/meghanada-emacs/issues/30
