### ISSUE TITLE
java.lang.NullPointerException: neither pomFile nor modelSource can be null

### ISSUE THREAD

**Issue by photex** [mopemope/meghanada-emacs#77]
Howdy!

No idea at all why or how this is happening. Nothing unusual about the project as far as I know. Works fine in the vscode java language server setup, can be imported without problem into Intellij.

Would love to be able to use Emacs as my daily driver for this project. 

Any tips on how to triage?

**Comment by photex** [comment]
Sorry here is the stacktrace:

```
[2017-11-22 11:36:54,584][INFO ][Main          : 125] main                   - Meghanada-Server Version:0.8.3-507f400
[2017-11-22 11:36:55,068][INFO ][MavenProject  :  71] parseProject           - running maven. resolve dependencies ...
[2017-11-22 11:36:58,980][ERROR][EmacsServer   : 311] startServer            - Catching
java.lang.NullPointerException: neither pomFile nor modelSource can be null
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:518) ~[meghanada-0.8.3.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1097) ~[meghanada-0.8.3.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829) ~[meghanada-0.8.3.jar:?]
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331) ~[meghanada-0.8.3.jar:?]
	at meghanada.project.maven.POMParser.parsePom(POMParser.java:84) ~[meghanada-0.8.3.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:98) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.loadProject(Session.java:188) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.findProject(Session.java:121) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:97) ~[meghanada-0.8.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:92) ~[meghanada-0.8.3.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:306) [meghanada-0.8.3.jar:?]
	at meghanada.Main.main(Main.java:127) [meghanada-0.8.3.jar:?]
```

**Comment by mopemope** [comment]
@photex Thank you for your report. Could you show me the pom file if possible?

**Comment by photex** [comment]
Sure thing. I've changed our company name to 'redacted' here. This probably isn't going to work for anyone outside of our corporate intranet since we have some internal dependencies. 

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.redacted.core.backend</groupId>
		<artifactId>core-base-parent</artifactId>
		<version>(,10000),[20000-SNAPSHOT]</version>
	</parent>

	<artifactId>core-socketserver</artifactId>
	<version>20000-SNAPSHOT</version>

	<properties>
		<akka.version>2.5.6</akka.version>
		<scala.abi>2.12</scala.abi>
	</properties>

	<dependencies>

		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-actor_${scala.abi}</artifactId>
			<version>${akka.version}</version>
		</dependency>

		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-slf4j_${scala.abi}</artifactId>
			<version>${akka.version}</version>
		</dependency>

		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>3.9</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http</artifactId>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-stomp</artifactId>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-handler</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.16.18</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
		</dependency>

		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.5.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java-util</artifactId>
			<version>3.4.0</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jdk8</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.9.2</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>1.5.8.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>2.7.2</version>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.1.4</version>
		</dependency>

		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-core</artifactId>
			<version>3.2.5</version>
		</dependency>

		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-healthchecks</artifactId>
			<version>3.2.5</version>
		</dependency>

		<dependency>
			<groupId>io.dropwizard.metrics</groupId>
			<artifactId>metrics-graphite</artifactId>
			<version>3.2.5</version>
		</dependency>


		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
			<version>4.2.0</version>
		</dependency>

		<dependency>
			<groupId>com.auth0</groupId>
			<artifactId>java-jwt</artifactId>
			<version>3.3.0</version>
		</dependency>


		<dependency>
			<groupId>io.lettuce</groupId>
			<artifactId>lettuce-core</artifactId>
			<version>5.0.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.1.2.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>5.0.0</version>
		</dependency>

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-bom</artifactId>
				<version>4.1.17.Final</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>20.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring.boot.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>


			<plugin>
				<groupId>com.github.os72</groupId>
				<artifactId>protoc-jar-maven-plugin</artifactId>
				<version>3.4.0.2</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<protocVersion>3.5.0</protocVersion>
							<includeStdTypes>true</includeStdTypes>
							<inputDirectories>
								<include>src/main/proto</include>
							</inputDirectories>
							<cleanOutputFolder>true</cleanOutputFolder>
							<outputTargets>
								<outputTarget>
									<type>java</type>
									<outputDirectory>target/generated-sources/proto</outputDirectory>
								</outputTarget>
							</outputTargets>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

	<repositories>
		<repository>
			<id>redacted-artifactory</id>
			<name>The Redacted Artifactory Relases Repository</name>
			<url>https://artifacts.redacted.de/redacted-maven</url>
		</repository>
		<repository>
			<id>snapshots</id>
			<name>The Redacted Artifactory Snapshots Repository</name>
			<url>https://artifacts.redacted.de/redacted-maven</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>redacted-artifactory</id>
			<name>The Redacted Artifactory Relases Repository</name>
			<url>https://artifacts.redacted.de/redacted-maven</url>
		</pluginRepository>
		<pluginRepository>
			<id>snapshots</id>
			<name>The Redacted Artifactory Snapshots Repository</name>
			<url>https://artifacts.redacted.de/redacted-maven</url>
		</pluginRepository>
	</pluginRepositories>

</project>

```
