### ISSUE TITLE
Gradle project jump declaration(M-.) fails

### ISSUE THREAD

**Issue by douglarek** [mopemope/meghanada-emacs#8]
@mopemope thanks for your great java mode for Emacs! I have some trouble with `jump declaration`

```
Warning: (end-of-file)
```

macOS && Emacs 25.1 && Gradle 2.14.1

Thanks

**Comment by mopemope** [comment]
Please try again latest version and call `M-x meghanada-install-server`. and Please report your warning log in `*meghanada-server-log*`and your code.

**Comment by douglarek** [comment]
@mopemope I just cloned `meghanada-server` source; and I got this:

```
[2016-09-20 11:25:52,080][WARN ][Session       : 499] jumpDeclaration        - missing location path=/Users/lingchax/work/java/meghanada-server/src/main/java/meghanada/Main.java line=91 column=33 symbol=createServer
[2016-09-20 11:25:52,249][WARN ][Session       : 499] jumpDeclaration        - missing location path=/Users/lingchax/work/java/meghanada-server/src/main/java/meghanada/Main.java line=91 column=32 symbol=createServer
[2016-09-20 11:25:52,418][WARN ][Session       : 499] jumpDeclaration        - missing location path=/Users/lingchax/work/java/meghanada-server/src/main/java/meghanada/Main.java line=91 column=31 symbol=createServer
[2016-09-20 11:25:52,587][WARN ][Session       : 499] jumpDeclaration        - missing location path=/Users/lingchax/work/java/meghanada-server/src/main/java/meghanada/Main.java line=91 column=30 symbol=createServer
[2016-09-20 11:25:52,756][ERROR][EmacsServer   : 115] lambda$acceptConnectio - null
java.lang.NullPointerException
	at meghanada.server.emacs.EmacsServer.lambda$null$0(EmacsServer.java:101) ~[meghanada.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_102]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_102]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$1(EmacsServer.java:102) ~[meghanada.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[2016-09-20 11:25:52,759][INFO ][EmacsServer   : 122] lambda$acceptConnectio - client disconnect
```

**Comment by mopemope** [comment]
@douglarek Meghanada does not yet support search in source code jar.
 Contributions are extremely welcome.
