### ISSUE TITLE
How to get around project not found error?

### ISSUE THREAD

**Issue by pseohy** [mopemope/meghanada-emacs#93]
I am not really used to java project directory layouts. I am working on a project that doesn't use the `gradle` or the `maven` build tool.

I got this error when I open a `.java` file from my project.

```
[2018-03-14 19:28:49,176][INFO ][Main          : 125] main                   - \
Meghanada-Server Version:0.9.2-57da97e                                          
[2018-03-14 19:28:49,184][ERROR][EmacsServer   : 311] startServer            - \
Catching                                                                        
java.lang.IllegalArgumentException: Project Not Found                           
    at meghanada.session.Session.lambda$createSession$0(Session.java:101) ~[meg\
hanada-0.9.2.jar:?]                                                             
    at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_161]         
    at meghanada.session.Session.createSession(Session.java:101) ~[meghanada-0.\
9.2.jar:?]                                                                      
    at meghanada.session.Session.createSession(Session.java:93) ~[meghanada-0.9\
.2.jar:?]                                                                       
    at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:306) [me\
ghanada-0.9.2.jar:?]                                                            
    at meghanada.Main.main(Main.java:127) [meghanada-0.9.2.jar:?]               
[2018-03-14 19:28:49,189][INFO ][Main          :  69] lambda$main$0          - \
shutdown server
```

I've used `sbt` and `ensime` with Scala, and I was only able to configure `ensime` with my project by passing `ensimeConfig` command to `sbt` shell.

Is `meghanada` works similar to `ensime`, in a sense that it requires specific directory structures fit for `gradle` or `maven`?

Will meghanada automatically find out a project if the directory root contains project built by `gradle` or `maven`?

And is it possible to use meghanada with a project that is not built by those build tools?

Thank you in advance.

**Comment by pseohy** [comment]
Thanks to #46 I've succeeded to configure my projects!
